# Assignment 2

As before, if a question can be answered with 'yes/no', or a numeric value, you may simply state as much. If you incorporate code from the internet (which is not required and generally not advisable), please cite the source within your code (providing a URL is sufficient).

We will go through comparable code and concepts in the live learning sessions. If you run into trouble, start by using the help `help()` function in Python, to get information about the datasets and function in question. The internet is also a great resource when coding (though note that no outside searches are required by the assignment!). If you do incorporate code from the internet, please cite the source within your code (providing a URL is sufficient).

Please bring questions that you cannot work out on your own to office hours, work periods or share with your peers on Slack. We will work with you through the issue.

If you like, you may collaborate with others in the cohort. If you choose to do so, please indicate with whom you have worked with in your pull request by tagging their GitHub username. Separate submissions are required.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm

# Import specific objects
from sklearn.preprocessing import StandardScaler
from ISLP import load_data

### Question 1: Classification using KNN

We'll now use the `Caravan` dataset from the `ISLP` package. (You may use `Caravan.describe()` to review details of the dataset.) In this dataset, the response variable of interest is `Purchase`, which indicates if a given customer purchased a caravan insurance policy. We will simultaneously use all other variables in the dataset to predict the response variable.

In [9]:
# Load the "Caravan" dataset using the "load_data" function from the ISLP package
Caravan = load_data('Caravan')
Caravan

# Add your code here

,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,MRELGE,...,APERSONG,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,Purchase
0,33,1,3,2,8,0,5,1,3,7,...,0,0,0,1,0,0,0,0,0,No
1,37,1,2,2,8,1,4,1,4,6,...,0,0,0,1,0,0,0,0,0,No
2,37,1,2,2,8,0,4,2,4,3,...,0,0,0,1,0,0,0,0,0,No
3,9,1,3,3,3,2,3,2,4,5,...,0,0,0,1,0,0,0,0,0,No
4,40,1,4,2,10,1,4,1,4,7,...,0,0,0,1,0,0,0,0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5817,36,1,1,2,8,0,6,1,2,1,...,0,0,0,1,0,0,0,0,0,No
5818,35,1,4,4,8,1,4,1,4,6,...,0,0,0,1,0,0,0,0,0,No
5819,33,1,3,4,8,0,6,0,3,5,...,0,0,0,1,0,0,0,0,0,Yes
5820,34,1,3,2,8,0,7,0,2,7,...,0,0,0,0,0,0,0,0,0,No
5821,33,1,3,3,8,0,6,1,2,7,...,0,0,0,0,0,0,0,0,0,No

In [7]:
Caravan.describe()

,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,MRELGE,...,ALEVEN,APERSONG,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND
count,5822.000000,5822.000000,5822.000000,5822.000000,5822.000000,5822.000000,5822.000000,5822.000000,5822.000000,5822.000000,...,5822.000000,5822.000000,5822.000000,5822.000000,5822.000000,5822.000000,5822.000000,5822.000000,5822.000000,5822.000000
mean,24.253349,1.110615,2.678805,2.991240,5.773617,0.696496,4.626932,1.069907,3.258502,6.183442,...,0.076606,0.005325,0.006527,0.004638,0.570079,0.000515,0.006012,0.031776,0.007901,0.014256
std,12.846706,0.405842,0.789835,0.814589,2.856760,1.003234,1.715843,1.017503,1.597647,1.909482,...,0.377569,0.072782,0.080532,0.077403,0.562058,0.022696,0.081632,0.210986,0.090463,0.119996
min,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,10.000000,1.000000,2.000000,2.000000,3.000000,0.000000,4.000000,0.000000,2.000000,5.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,30.000000,1.000000,3.000000,3.000000,7.000000,0.000000,5.000000,1.000000,3.000000,6.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,35.000000,1.000000,3.000000,3.000000,8.000000,1.000000,6.000000,2.000000,4.000000,7.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,41.000000,10.000000,5.000000,6.000000,10.000000,9.000000,9.000000,5.000000,9.000000,9.000000,...,8.000000,1.000000,1.000000,2.000000,7.000000,1.000000,2.000000,3.000000,2.000000,2.000000

Before fitting any model, it is essential to understand our data. Answer the following questions about the `Caravan` dataset (Hint: use `print` and `describe`):  
_(i)_ How many observations (rows) does the dataset contain?    5822
_(ii)_ How many variables (columns) does the dataset contain?    86
_(iii)_ What 'variable' type is the response variable `Purchase` (e.g., 'character', 'factor', 'numeric', etc)? What are the 'levels' of the variable?   

array(['No', 'Yes'], dtype=object)
85  Purchase  5822 non-null   object

_(iv)_ How many predictor variables do we have (Hint: all variables other than `Purchase`)?  85

In [18]:
# Add your code here    
Caravan.shape[0]

5822

In [20]:
Caravan.shape[1]

86

In [32]:
print(Caravan['Purchase'].dtypes)

object

In [34]:
Caravan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5822 entries, 0 to 5821
Data columns (total 86 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   MOSTYPE   5822 non-null   int64
 1   MAANTHUI  5822 non-null   int64
 2   MGEMOMV   5822 non-null   int64
 3   MGEMLEEF  5822 non-null   int64
 4   MOSHOOFD  5822 non-null   int64
 5   MGODRK    5822 non-null   int64
 6   MGODPR    5822 non-null   int64
 7   MGODOV    5822 non-null   int64
 8   MGODGE    5822 non-null   int64
 9   MRELGE    5822 non-null   int64
 10  MRELSA    5822 non-null   int64
 11  MRELOV    5822 non-null   int64
 12  MFALLEEN  5822 non-null   int64
 13  MFGEKIND  5822 non-null   int64
 14  MFWEKIND  5822 non-null   int64
 15  MOPLHOOG  5822 non-null   int64
 16  MOPLMIDD  5822 non-null   int64
 17  MOPLLAAG  5822 non-null   int64
 18  MBERHOOG  5822 non-null   int64
 19  MBERZELF  5822 non-null   int64
 20  MBERBOER  5822 non-null   int64
 21  MBERMIDD  5822 non-null   int64
 22  MBERARBG  5822 non-null   int64
 23  MBERARBO  5822 non-null   int64
 24  MSKA      5822 non-null   int64
 25  MSKB1     5822 non-null   int64
 26  MSKB2     5822 non-null   int64
 27  MSKC      5822 non-null   int64
 28  MSKD      5822 non-null   int64
 29  MHHUUR    5822 non-null   int64
 30  MHKOOP    5822 non-null   int64
 31  MAUT1     5822 non-null   int64
 32  MAUT2     5822 non-null   int64
 33  MAUT0     5822 non-null   int64
 34  MZFONDS   5822 non-null   int64
 35  MZPART    5822 non-null   int64
 36  MINKM30   5822 non-null   int64
 37  MINK3045  5822 non-null   int64
 38  MINK4575  5822 non-null   int64
 39  MINK7512  5822 non-null   int64
 40  MINK123M  5822 non-null   int64
 41  MINKGEM   5822 non-null   int64
 42  MKOOPKLA  5822 non-null   int64
 43  PWAPART   5822 non-null   int64
 44  PWABEDR   5822 non-null   int64
 45  PWALAND   5822 non-null   int64
 46  PPERSAUT  5822 non-null   int64
 47  PBESAUT   5822 non-null   int64
 48  PMOTSCO   5822 non-null   int64
 49  PVRAAUT   5822 non-null   int64
 50  PAANHANG  5822 non-null   int64
 51  PTRACTOR  5822 non-null   int64
 52  PWERKT    5822 non-null   int64
 53  PBROM     5822 non-null   int64
 54  PLEVEN    5822 non-null   int64
 55  PPERSONG  5822 non-null   int64
 56  PGEZONG   5822 non-null   int64
 57  PWAOREG   5822 non-null   int64
 58  PBRAND    5822 non-null   int64
 59  PZEILPL   5822 non-null   int64
 60  PPLEZIER  5822 non-null   int64
 61  PFIETS    5822 non-null   int64
 62  PINBOED   5822 non-null   int64
 63  PBYSTAND  5822 non-null   int64
 64  AWAPART   5822 non-null   int64
 65  AWABEDR   5822 non-null   int64
 66  AWALAND   5822 non-null   int64
 67  APERSAUT  5822 non-null   int64
 68  ABESAUT   5822 non-null   int64
 69  AMOTSCO   5822 non-null   int64
 70  AVRAAUT   5822 non-null   int64
 71  AAANHANG  5822 non-null   int64
 72  ATRACTOR  5822 non-null   int64
 73  AWERKT    5822 non-null   int64
 74  ABROM     5822 non-null   int64
 75  ALEVEN    5822 non-null   int64
 76  APERSONG  5822 non-null   int64
 77  AGEZONG   5822 non-null   int64
 78  AWAOREG   5822 non-null   int64
 79  ABRAND    5822 non-null   int64
 80  AZEILPL   5822 non-null   int64
 81  APLEZIER  5822 non-null   int64
 82  AFIETS    5822 non-null   int64
 83  AINBOED   5822 non-null   int64
 84  ABYSTAND  5822 non-null   int64
 85  Purchase  5822 non-null   object
dtypes: int64(85), object(1)
memory usage: 3.8+ MB

In [36]:
Caravan['Purchase'].unique()

array(['No', 'Yes'], dtype=object)

Next, we must preform 'pre-processing' or 'data munging', to prepare our data for classification/prediction. For KNN, there are three essential steps. A first essential step is to 'standardize' the predictor variables. We can achieve this using the `scaler` method, provided as follows:

In [37]:
# Select predictors (excluding the 86th column)
predictors = Caravan.iloc[:, :-1]

# Standardize the predictors
scaler = StandardScaler()
predictors_standardized = pd.DataFrame(scaler.fit_transform(predictors), columns=predictors.columns)

# Display the head of the standardized predictors
print(predictors_standardized.head())

    MOSTYPE  MAANTHUI   MGEMOMV  MGEMLEEF  MOSHOOFD    MGODRK    MGODPR  \
0  0.680906  -0.27258  0.406697 -1.216964  0.779405 -0.694311  0.217444
1  0.992297  -0.27258 -0.859500 -1.216964  0.779405  0.302552 -0.365410
2  0.992297  -0.27258 -0.859500 -1.216964  0.779405 -0.694311 -0.365410
3 -1.187437  -0.27258  0.406697  0.010755 -0.970980  1.299414 -0.948264
4  1.225840  -0.27258  1.672893 -1.216964  1.479559  0.302552 -0.365410

     MGODOV    MGODGE    MRELGE  ...   ALEVEN  APERSONG   AGEZONG  AWAOREG  \
0 -0.068711 -0.161816  0.427670  ... -0.20291 -0.073165 -0.081055 -0.05992
1 -0.068711  0.464159 -0.096077  ... -0.20291 -0.073165 -0.081055 -0.05992
2  0.914172  0.464159 -1.667319  ... -0.20291 -0.073165 -0.081055 -0.05992
3  0.914172  0.464159 -0.619824  ... -0.20291 -0.073165 -0.081055 -0.05992
4 -0.068711  0.464159  0.427670  ... -0.20291 -0.073165 -0.081055 -0.05992

     ABRAND   AZEILPL  APLEZIER   AFIETS   AINBOED  ABYSTAND
0  0.764971 -0.022706  -0.07365 -0.15062 -0.087348 -0.118816
1  0.764971 -0.022706  -0.07365 -0.15062 -0.087348 -0.118816
2  0.764971 -0.022706  -0.07365 -0.15062 -0.087348 -0.118816
3  0.764971 -0.022706  -0.07365 -0.15062 -0.087348 -0.118816
4  0.764971 -0.022706  -0.07365 -0.15062 -0.087348 -0.118816

[5 rows x 85 columns]

_(v)_ Why is it important to standardize the predictor variables?  

Ans. When predictor variables are on different scales, the coefficients obtained from a regression model may not be directly comparable.

_(vi)_ Why did we elect not to standard our response variable `Purchase`?  
Ans. Purchase column has only two responses (yes or no). So don't need to standardize the reponse.

In [ ]:
# Your answer here


_(vii)_ A second essential step is to set a random seed. Do so below (Hint: use the `random.seed` function). Why is setting a seed important? Is the particular seed value important? Why or why not?

In [41]:
# Add your code here
np.random.seed(55)

# Ans. every time you run the program with the same seed value, you'll get the same sequence of random numbers. Using random.seed() is particularly useful in situations where you need to debug code that involves randomness or when you want to ensure that your results are reproducible

_(viii)_ A third essential step is to split our standardized data into separate training and testing sets. We will split into 75% training and 25% testing. The provided code randomly partitions our data, and creates linked training sets for the predictors and response variables. Extend the code to create a non-overlapping test set for the predictors and response variables.

In [42]:
# Create a random vector of True and False values
split = np.random.choice([True, False], size=len(predictors_standardized), replace=True, p=[0.75, 0.25])

# Define the training set for X (predictors)
training_X = predictors_standardized[split]

# Define the training set for Y (response)
training_Y = Caravan.loc[split, 'Purchase']

# Define the testing set for X (predictors)
testing_X = predictors_standardized[~split]

# Define the testing set for Y (response)
testing_Y = Caravan.loc[~split, 'Purchase']

_(ix)_ We are finally set to fit the KNN model. In Python, we can use the `KNeighborsClassifier()` function. Fit the KNN with k=1. (You may review arguments to knn by typing `help(knn.fit)`).

In [44]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [46]:
help(knn.fit)

Help on method fit in module sklearn.neighbors._classification:

fit(X, y) method of sklearn.neighbors._classification.KNeighborsClassifier instance
    Fit the k-nearest neighbors classifier from the training dataset.

    Parameters
    ----------
    X : {array-like, sparse matrix} of shape (n_samples, n_features) or                 (n_samples, n_samples) if metric='precomputed'
        Training data.

    y : {array-like, sparse matrix} of shape (n_samples,) or                 (n_samples, n_outputs)
        Target values.

    Returns
    -------
    self : KNeighborsClassifier
        The fitted k-nearest neighbors classifier.

Using your fit model, answer the following questions:   
_(x)_ What is the prediction accuracy? (Hint: use the `score` method, and compare your model to `testing_Y`)  
_(xi)_ What is the predictor error ? (Hint: compute it from the accuracy)

In [ ]:
# prediction accuracy rate

In [ ]:
# prediction error rate

_(xii)_ How does this prediction error/accuracy compare to what could be achieved via random guesses? To answer this, consider the percent of customers in the `Caravan` dataset who actually purchase insurance, computed below:

In [ ]:
# Calculate the percentage of customers who purchase insurance
percentage_purchase = (Caravan['Purchase'].eq('Yes').sum() / len(Caravan['Purchase'])) * 100

print(percentage_purchase)

_(xiii)_ Fit a second KNN model, with $K=3$. Does this model perform better (i.e., have higher accuracy, compared to a random guess)?

In [ ]:
# Your code here

# Criteria

|Criteria            |Complete           |Incomplete          |
|--------------------|---------------|--------------|
|Classification using KNN|All steps are done correctly and the answers are correct.|At least one step is done incorrectly leading to a wrong answer.|

## Submission Information

🚨 **Please review our [Assignment Submission Guide](https://github.com/UofT-DSI/onboarding/blob/main/onboarding_documents/submissions.md)** 🚨 for detailed instructions on how to format, branch, and submit your work. Following these guidelines is crucial for your submissions to be evaluated correctly.

### Submission Parameters:
* Submission Due Date: `HH:MM AM/PM - DD/MM/YYYY`
* The branch name for your repo should be: `assignment-2`
* What to submit for this assignment:
    * This Jupyter Notebook (assignment_2.ipynb) should be populated and should be the only change in your pull request.
* What the pull request link should look like for this assignment: `https://github.com/<your_github_username>/applied_statistical_concepts/pull/<pr_id>`
    * Open a private window in your browser. Copy and paste the link to your pull request into the address bar. Make sure you can see your pull request properly. This helps the technical facilitator and learning support staff review your submission easily.

Checklist:
- [ ] Created a branch with the correct naming convention.
- [ ] Ensured that the repository is public.
- [ ] Reviewed the PR description guidelines and adhered to them.
- [ ] Verify that the link is accessible in a private browser window.

If you encounter any difficulties or have questions, please don't hesitate to reach out to our team via our Slack at `#cohort-3-help`. Our Technical Facilitators and Learning Support staff are here to help you navigate any challenges.